### ISSUE TITLE
Imputation

### ISSUE THREAD

**Issue by WeiYang-BAI** [gymrek-lab/EnsembleTR#14]
Hi, 

Thanks for this wonderful reference panel for TR imputation! Not an issue, just wondering could I use other tools instead of beagle for the imputation? Would beagle perform better with the panel?

Best,

**Comment by heliziii** [comment]
Hi! I'm sorry for the late reply. You surely can use other tools for imputation. However, based on our experience, Beagle works more accurately in the imputation of multi-allelic sites like TRs.

Best,
Helia

**Comment by WeiYang-BAI** [comment]
> 

See it, thanks Helia!

Best,
Weiyang
