### ISSUE TITLE
Could I use this software in the plant genome?

### ISSUE THREAD

**Issue by HaoWangLYL** [gymrek-lab/EnsembleTR#15]
Could I use this software in the plant genome?

**Comment by heliziii** [comment]
Hi! I am sorry for the late reply. Yes, as long as you have TR calls from at least a couple of TR genotypers (like HipSTR or ExpansionHunter) in your genome, you can use EnsembleTR to output the consensus calls based on them.

**Comment by HaoWangLYL** [comment]
Ok, thank you~&nbsp;


635169288
***@***.***



&nbsp;
