### ISSUE TITLE
Can you share the reference sites of GangSTR and adVNTR?

### ISSUE THREAD

**Issue by YiweiNiu** [gymrek-lab/EnsembleTR#16]
Hi,

Congrats to the great work. I wonder if you could share the reference sites you used for GangSTR and adVNTR.

Bests,
Yiwei

**Comment by heliziii** [comment]
Hi,

Thank you very much for your interest in our work! 

HipSTR reference file was downloaded from the HipSTR website:
https://github.com/HipSTR-Tool/HipSTR-references/blob/master/human/GRCh38.hipstr_reference.bed.gz

For GangSTR, you can see the reference sites here:
https://github.com/gymrek-lab/EnsembleTR/blob/main/hg38_info_full.bed

**Comment by YiweiNiu** [comment]
Thank you for your reply. Thank you for the reference sites.
