### ISSUE TITLE
Questions about the output of EnsembleTR

### ISSUE THREAD

**Issue by wjzzq** [gymrek-lab/EnsembleTR#21]
[test.docx](https://github.com/gymrek-lab/EnsembleTR/files/13915483/test.docx)
Hi,  Noma

When I merged HIpSTR, GangSTR, and EH with EnsembleTR, I found that there were many sites that appeared twice, but they were in the same position and the repeat motif were the same.

Curious why this part isn't merged, should one of them be filtered?

Best wishes！
Zhiqin

**Comment by heliziii** [comment]
Hi Zhiqin,

Technically they should be merged, are all your input files sorted before being given to EnsembleTR as input? Is it possible for you to send me a small part of your input files so I can regenerate the issue?

Best,
Helyaneh

**Comment by wjzzq** [comment]
[sample.zip](https://github.com/gymrek-lab/EnsembleTR/files/14017708/sample.zip)

Yes, I have sorted. The attachment is part of my input file, I merged them with EnsembleTR, and I got Ensemble_merged.vcf. Some loci in Ensemble_merged.vcf were still found to appear twice.


Thank you for your reply.

Best wishes!

Zhiqin

**Comment by wjzzq** [comment]
[sample.zip](https://github.com/gymrek-lab/EnsembleTR/files/14060978/sample.zip)

Yes, I have sorted. The attachment is part of my input file, I merged them with EnsembleTR, and I got Chr8-UN.vcf. Some loci in Chr8-UN.vcf were still found to appear twice. 

For example, for the Cru-Chr8:8974020 locus, I think it would be reasonable for HIpSTR and GangSTR to be identified as one locus, but there are two loci after the merger by EnsembleTR.

```
Cru-Chr8	8974020	.	AGATTAAAAAGAAAAGAAAAAGAAAAA	AGATTAAAAAGAAAAGAAAAAGAAAAAA	.	.	START=8974020;END=8974046;PERIOD=6;RU=AAAAGG;METHODS=0|0|1|0	GT:GB:NCOPY:EXP:SCORE:GTS:ALS:INPUTS	.:.:.:.:.:.:.:hipstr=.
Cru-Chr8	8974020	.	AAAAAGAAAAAGAAAAAG	AAAAAG,AAAAAGAAAAAG,AAAAAGAAAAAGAAAAAGAAAAAG,AAAAAGAAAAAGAAAAAGAAAAAGAAAAAG,AAAAAGAAAAAGAAAAAGAAAAAGAAAAAGAAAAAG	.	.	START=8974020;END=8974037;PERIOD=6;RU=AAAAAG;METHODS=0|0|0|1	GT:GB:NCOPY:EXP:SCORE:GTS:ALS:INPUTS	.:.:.:.:.:.:.:gangstr=.
```


Thank you for your reply.

Best wishes!

Zhiqin

**Comment by heliziii** [comment]
Hi Zhiqin,

At least for this example what happened is that the motif sequences are different, for HipSTR, the motif is "AAAAGG" and for GangSTR is "AAAAAG", which is why EnsembleTR did not merge them. HipSTR doesn't report the motif sequence, and it is inferred by TRTools, a library we use in EnsembleTR. Although, weirdly, it inferred "AAAAGG" here, I don't think EnsembleTR is doing something wrong. I would be happy to look at more examples of not merged calls. 

Best,
Helia
