### ISSUE TITLE
python libraries version error while installing EnsembleTR

### ISSUE THREAD

**Issue by Schahrjar** [gymrek-lab/EnsembleTR#23]
Installation of EnsembleTR on Ubuntu returns multiple version errors. Some require newer versions of what I have, and some require older versions. For example scikit aks for python3.9 (I have python3.8) while EnsembleTR calls old versions of numpy.

Seems that the tool requires a specific assembly of dependencies. Is this possible to have a precompiled version of EnsembleTR?

Many thanks!

**Comment by heliziii** [comment]
Hi Shahriyar,

I apologize for the late reply. I have been working on solving the issue with package incompatibility. Can you please try and see if the following will install ensembletr:


```
pip install --upgrade pip
pip install ensembletr
```

you can then test it by

`ensembletr --vcfs hipstr.vcf,gangstr.vcf --out ensemble.vcf --ref ref.fa`

Best,
Helia

**Comment by Schahrjar** [comment]
Great! Thanks Helia.

I installed via pip and then ran the `ensembletr --help` command, printed the help message.

Kind,
Shahryar
