### ISSUE TITLE
merging HipSTR VCF results before EnsembleTR

### ISSUE THREAD

**Issue by xbwdk** [gymrek-lab/EnsembleTR#24]
Hi Helia and EnsembleTR developers,

I plan to use EnsembleTR to merge results from different TR callers. For HipSTR, I divided my samples in few batches and run HipSTR on each batch. As for the merging step, I noticed that the latest version of mergeSTR is v6.0.1, but the Nat. Commun. paper mentioned a specific branch of mergeSTR (https://github.com/gymrek-lab/TRTools/tree/conf_ref). May I ask if one is better than another for HipSTR merging, please? For example, if Hipstr_correction.py only works well on the conf_ref version? 
Since it is more convenient for me to install and run the main version through bioconda, I would prefer using v6.0.1 if both versions work equally well.

Thank you very much :) 

Best,
xbwdk

**Comment by heliziii** [comment]
Hello,

Thank you for your interest in using EnsembleTR! Please use the latest version of mergeSTR (v6.0.1) and then run Hipstr_correction.py on its output. 

There used to be an issue with merging records with the same REF position but not it is resolved in mergeSTR, so no need to use the conf_ref version.

Best,
Helia
